spring:
  application:
    name: library-management-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_db
    username: ${DB_USERNAME:library_user}
    password: ${DB_PASSWORD:library_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.upcode.lms: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# Swagger/OpenAPI Documentation
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    displayOperationId: false
  show-actuator: false
  # Auto-detection settings
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  # Auto-generate documentation from method names and parameters
  writer-with-default-pretty-printer: true
  # Automatically detect security schemes
  auto-tag-classes: true
  # Generate operation IDs from method names
  use-management-port: false
  group-configs:
    - group: 'public'
      display-name: 'Public APIs'
      paths-to-match: '/categories/**,/test/**'
    - group: 'auth'
      display-name: 'Authentication APIs'  
      paths-to-match: '/auth/**'
    - group: 'admin'
      display-name: 'Admin APIs'
      paths-to-match: '/admin/**'

app:
  library:
    max-books-per-user: 5
    loan-duration-days: 14
    fine-per-day: 5.0
    reservation-hold-days: 3
    max-renewal-count: 2